In [ ]:
#importing tensorflow
import tensorflow as tf

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Create a scalar (rank 0 tensor)
scalar = tf.constant(7)
scalar

In [ ]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# Create a vector (more than 0 dimensions)
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:

# Create a matrix (more than 1 dimension)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:

matrix.ndim

2

In [ ]:

# How about a tensor? (more than 2 dimensions, although, all of the above items are also technically tensors)
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:

tensor.ndim

3

In [ ]:
# scalar: a single number.
# vector: a number with direction (e.g. wind speed with direction).
# matrix: a 2-dimensional array of numbers.
# tensor: an n-dimensional arrary of numbers (where n can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector).

In [ ]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:

# Shuffle a tensor (valuable for when you want to shuffle your data)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
# Gets different results each time
tf.random.shuffle(not_shuffled, seed=42)

In [ ]:
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor



In [ ]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

In [ ]:

# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])


In [ ]:

tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means last axis

In [ ]:

# You can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

In [ ]:

# Multiplication (known as element-wise multiplication)
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:

# Subtraction
tensor - 10

In [ ]:

# Use the tensorflow function equivalent of the '*' (multiply) operator
tf.multiply(tensor, 10)

In [ ]:

# Create (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

In [ ]:
tf.reshape(Y, shape=(2, 3))

In [ ]:
X @ tf.reshape(Y, shape=(2, 3))

In [ ]:
# Example of transpose (3, 2) -> (2, 3)
tf.transpose(X)

In [ ]:

# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])

B

In [ ]:

# Change from float32 to float16 (reduced precision)
B = tf.cast(B, dtype=tf.float16)
B

In [ ]:
x = tf.constant([[1,2],[2,1],[3,4]])

In [ ]:

# Find the minimum
tf.reduce_min(X)

In [ ]:

# Find the maximum
tf.reduce_max(X)

In [ ]:

# Find the mean
tf.reduce_mean(X)


In [ ]:
# Find the sum
tf.reduce_sum(X)

In [ ]:

# Find the maximum element position of F
tf.argmax(X)


<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [ ]:
# Find the minimum element position of F
tf.argmin(X)

In [ ]:
rank_4_tensor = tf.zeros([1,1,1,5])
rank_4_tensor

In [ ]:

# Squeeze tensor G (remove all 1 dimensions)
rank4_squeezed = tf.squeeze(rank_4_tensor)
rank4_squeezed